export const questions = {
  moduleA: [
    {
      id: "q_mod_a_1",
      questionNumber: 1,
      totalInModule: 5,
      module: "A",
      moduleTitle: "SYSTEM KNOWLEDGE CHECK",
      prompt: "What is the output of an AND gate when one of its inputs is LOW?",
      options: [
        { key: "A", text: "HIGH" },
        { key: "B", text: "LOW" },
        { key: "C", text: "Floating" },
        { key: "D", text: "Undefined" },
      ],
      correctAnswer: "B",
      explanation: "An AND gate requires all inputs to be HIGH (1) to produce a HIGH output. If any input is LOW (0), the output is immediately LOW (0).",
    },
    {
      id: "q_mod_a_2",
      questionNumber: 2,
      totalInModule: 5,
      module: "A",
      moduleTitle: "SYSTEM KNOWLEDGE CHECK",
      prompt: "Which logic gate produces HIGH only when its two inputs are different?",
      options: [
        { key: "A", text: "AND" },
        { key: "B", text: "OR" },
        { key: "C", text: "NOT" },
        { key: "D", text: "XOR" },
      ],
      correctAnswer: "D",
      explanation: "An XOR (Exclusive OR) gate outputs HIGH (1) strictly when its inputs are distinct (0,1 or 1,0). When both inputs are identical (0,0 or 1,1), its output is LOW (0).",
    },
    {
      id: "q_mod_a_3",
      questionNumber: 3,
      totalInModule: 5,
      module: "A",
      moduleTitle: "SYSTEM KNOWLEDGE CHECK",
      prompt: "Which logic gate performs digital signal inversion where the output is the logical complement of the input?",
      options: [
        { key: "A", text: "Buffer gate" },
        { key: "B", text: "NOT gate (Inverter)" },
        { key: "C", text: "NAND gate" },
        { key: "D", text: "NOR gate" },
      ],
      correctAnswer: "B",
      explanation: "A NOT gate (Inverter) inverts the incoming binary signal: a HIGH (1) input yields a LOW (0) output, and a LOW (0) input yields a HIGH (1) output.",
    },
    {
      id: "q_mod_a_4",
      questionNumber: 4,
      totalInModule: 5,
      module: "A",
      moduleTitle: "SYSTEM KNOWLEDGE CHECK",
      prompt: "What is the output of a 2-input OR gate when input A is HIGH (1) and input B is LOW (0)?",
      options: [
        { key: "A", text: "LOW (0)" },
        { key: "B", text: "HIGH (1)" },
        { key: "C", text: "High-Impedance (Z)" },
        { key: "D", text: "Oscillating" },
      ],
      correctAnswer: "B",
      explanation: "An OR gate produces a HIGH (1) output if at least one of its inputs is HIGH. Thus, 1 OR 0 evaluates to 1.",
    },
    {
      id: "q_mod_a_5",
      questionNumber: 5,
      totalInModule: 5,
      module: "A",
      moduleTitle: "SYSTEM KNOWLEDGE CHECK",
      prompt: "Which universal logic gate produces a LOW (0) output ONLY when all of its inputs are HIGH (1)?",
      options: [
        { key: "A", text: "NOR gate" },
        { key: "B", text: "XOR gate" },
        { key: "C", text: "NAND gate" },
        { key: "D", text: "XNOR gate" },
      ],
      correctAnswer: "C",
      explanation: "A NAND gate is an inverted AND gate (NOT-AND). Its output is LOW (0) strictly when all inputs are 1; for all other input combinations, it outputs HIGH (1).",
    },
  ],

  moduleB: [
    {
      id: "q_mod_b_1",
      questionNumber: 1,
      totalInModule: 1,
      module: "B",
      moduleTitle: "CIRCUIT LOGIC VERIFICATION",
      prompt: "Which gate should be used when ALL required safety conditions must be TRUE for the final output to become HIGH?",
      options: [
        { key: "A", text: "AND" },
        { key: "B", text: "OR" },
        { key: "C", text: "XOR" },
        { key: "D", text: "NOT" },
      ],
      correctAnswer: "A",
      explanation: "An AND gate enforces a strict conjunction: every single monitored safety interlock signal must evaluate to TRUE (1) to produce an active SAFE output.",
    },
  ],

  moduleC: [
    {
      id: "q_mod_c_1",
      questionNumber: 1,
      totalInModule: 5,
      module: "C",
      moduleTitle: "FAIL-SAFE PROTOCOL CHECK",
      prompt: "What should happen to the safety output if an emergency bypass is activated?",
      options: [
        { key: "A", text: "Remain HIGH" },
        { key: "B", text: "Become LOW (Safe State)" },
        { key: "C", text: "Toggle randomly" },
        { key: "D", text: "Increase voltage" },
      ],
      correctAnswer: "B",
      explanation: "In an industrial fail-safe interlock, activating an emergency bypass forces the primary safety output LOW to halt hazardous operations.",
    },
    {
      id: "q_mod_c_2",
      questionNumber: 2,
      totalInModule: 5,
      module: "C",
      moduleTitle: "FAIL-SAFE PROTOCOL CHECK",
      prompt: "In a fail-safe system, what is the default action when power is lost or a sensor fails?",
      options: [
        { key: "A", text: "Continue running normally" },
        { key: "B", text: "Automatically shut down into a safe state" },
        { key: "C", text: "Speed up all machinery" },
        { key: "D", text: "Disable error warnings" },
      ],
      correctAnswer: "B",
      explanation: "A fail-safe system is designed to automatically revert to a safe, de-energized shutdown state whenever a fault or power loss occurs.",
    },
    {
      id: "q_mod_c_3",
      questionNumber: 3,
      totalInModule: 5,
      module: "C",
      moduleTitle: "FAIL-SAFE PROTOCOL CHECK",
      prompt: "What is the primary purpose of an Emergency Stop (E-Stop) switch?",
      options: [
        { key: "A", text: "To restart the computer monitor" },
        { key: "B", text: "To immediately halt all hazardous machine movement" },
        { key: "C", text: "To increase conveyor speed" },
        { key: "D", text: "To calibrate sensor parameters" },
      ],
      correctAnswer: "B",
      explanation: "The E-Stop switch gives operators an instant way to cut power to hazardous machinery during an emergency.",
    },
    {
      id: "q_mod_c_4",
      questionNumber: 4,
      totalInModule: 5,
      module: "C",
      moduleTitle: "FAIL-SAFE PROTOCOL CHECK",
      prompt: "Why do critical safety systems use redundancy (dual sensors)?",
      options: [
        { key: "A", text: "So safety protection continues working even if one sensor fails" },
        { key: "B", text: "To increase electricity consumption" },
        { key: "C", text: "To eliminate the need for wires" },
        { key: "D", text: "To make the machine run twice as fast" },
      ],
      correctAnswer: "A",
      explanation: "Redundancy prevents a single sensor failure from causing an accident by maintaining a backup safety check.",
    },
    {
      id: "q_mod_c_5",
      questionNumber: 5,
      totalInModule: 5,
      module: "C",
      moduleTitle: "FAIL-SAFE PROTOCOL CHECK",
      prompt: "After an emergency stop is triggered, why must a manual reset be required to restart?",
      options: [
        { key: "A", text: "To allow machines to cool down automatically" },
        { key: "B", text: "To prevent unexpected startup while people are still in the danger zone" },
        { key: "C", text: "To clear computer internet cache" },
        { key: "D", text: "To reduce electrical power bills" },
      ],
      correctAnswer: "B",
      explanation: "A deliberate manual reset ensures operators visually confirm the hazard is cleared before machines restart.",
    },
  ],
};
